{% set name = "xsdata" %}
{% set version = "26.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dcae2c0e5f329f1b4e09a2d148c96941c9556616bb5e3418970a63c5eb2cd831

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - xsdata = xsdata.cli:cli

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - click >=5.0
    - jinja2 >=2.10
    - lxml >=4.5.0
    - requests
    - ruff >=0.9.8
    - toposort >=1.5
    - typing-extensions >=4.7.0

test:
  requires:
    - pytest
    - pytest-benchmark
    - python {{ python_min }}
  source_files:
    - tests/*
  commands:
    - pytest --benchmark-skip
    - xsdata --help


about:
  home: https://github.com/tefra/xsdata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Naive XML Bindings for python
  description: |
    xsData is a complete data binding library for python allowing developers
    to access and use XML and JSON documents as simple objects rather than
    using DOM.
  doc_url: https://xsdata.readthedocs.io
  dev_url: https://github.com/tefra/xsdata

extra:
  recipe-maintainers:
    - tefra
