{% set name = "xsdata" %}
{% set version = "21.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e99da614ab385a6a633f069c1beb831e9c1833a56dbc49c3c8123444a93557ac

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - xsdata = xsdata.cli:cli

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - click
    - click-default-group
    - click-log
    - docformatter
    - jinja2
    - lxml
    - requests
    - toposort
    - dataclasses
    - importlib-metadata

test:
  requires:
    - pytest
    - pytest-benchmark
  source_files:
    - tests/*
  commands:
    - pytest --benchmark-skip
    - xsdata --help


about:
  home: https://github.com/tefra/xsdata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Naive XML Bindings for python
  description: |
    xsData is a complete data binding library for python allowing developers
    to access and use XML and JSON documents as simple objects rather than
    using DOM.
  doc_url: https://xsdata.readthedocs.io
  dev_url: https://github.com/tefra/xsdata

extra:
  recipe-maintainers:
    - tefra
