{% set name = "xsdata" %}
{% set version = "21.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0cfb016450ff9e7bc6121e78d54b637a1e0114ca247b5f35be5e3d416d11d03b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - xsdata = xsdata.cli:cli

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - setuptools
    - click
    - click-default-group
    - click-log
    - docformatter
    - jinja2
    - lxml
    - requests
    - toposort
    - dataclasses
    - importlib-metadata

test:
  requires:
    - pytest
    - pytest-benchmark
  source_files:
    - tests/*
  commands:
    - pytest --benchmark-skip
    - xsdata --help


about:
  home: https://github.com/tefra/xsdata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Naive XML Bindings for python
  description: |
    xsData is a complete data binding library for python allowing developers
    to access and use XML and JSON documents as simple objects rather than
    using DOM.
  doc_url: https://xsdata.readthedocs.io
  dev_url: https://github.com/tefra/xsdata

extra:
  recipe-maintainers:
    - tefra
