{% set name = "xsdata" %}
{% set version = "24.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e36fc8b4624bbbaf2d34d0857c6d78ede99ec1d3240cc7dd50546177fbb52442

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - xsdata = xsdata.cli:cli

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - click >=5.0
    - click-default-group >=1.2
    - docformatter >=1.7.2
    - jinja2 >=2.10
    - lxml >=4.4.1
    - requests
    - ruff >=0.1.9
    - toposort >=1.5
    - typing-extensions

test:
  requires:
    - pytest
    - pytest-benchmark
  source_files:
    - tests/*
  commands:
    - pytest --benchmark-skip
    - xsdata --help


about:
  home: https://github.com/tefra/xsdata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Naive XML Bindings for python
  description: |
    xsData is a complete data binding library for python allowing developers
    to access and use XML and JSON documents as simple objects rather than
    using DOM.
  doc_url: https://xsdata.readthedocs.io
  dev_url: https://github.com/tefra/xsdata

extra:
  recipe-maintainers:
    - tefra
